/*загрузка списка нотификейшенов*/
export const START_LOAD_NOTIFICATIONS = 'START_LOAD_NOTIFICATIONS';
export const FINISH_LOAD_NOTIFICATIONS = 'FINISH_LOAD_NOTIFICATIONS';
export const ERROR_LOAD_NOTIFICATIONS = 'ERROR_LOAD_NOTIFICATIONS';

/*обновление*/
export const START_UPDATE_NOTIFICATIONS = "START_UPDATE_NOTIFICATIONS";
export const FINISH_UPDATE_NOTIFICATIONS = "FINISH_UPDATE_NOTIFICATIONS";
export const ERROR_UPDATE_NOTIFICATIONS = "ERROR_UPDATE_NOTIFICATIONS";

/*загрузка шаблона*/
export const START_LOAD_NOTIFICATION_TEMPLATE = 'START_LOAD_NOTIFICATION_TEMPLATE';
export const FINISH_LOAD_NOTIFICATION_TEMPLATE = 'FINISH_LOAD_NOTIFICATION_TEMPLATE';
export const ERROR_LOAD_NOTIFICATION_TEMPLATE = 'ERROR_LOAD_NOTIFICATION_TEMPLATE';